- hosts: localhost
  become: yes
  tasks:
    - name: Adicionar repositórios necessários
      block:
        - name: Adicionar repositório do GitHub CLI
          shell: |
            type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

    - name: Atualize todos os pacotes
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instale pacotes necessários
      apt:
        name:
          - curl
          - wget
          - git
          - zsh
          - vim
          - neovim
          - unzip
          - gh
        state: present

    - name: Instalar Homebrew
      become_user: "{{ ansible_user_id }}"
      ansible.builtin.shell: 
        cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        creates: "{{ ansible_env.HOME }}/.linuxbrew/bin/brew"

    - name: Adicionar Homebrew ao PATH
      become_user: "{{ ansible_user_id }}"
      blockinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        block: |
          # Homebrew configuration
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        create: yes
        marker: "# {mark} HOMEBREW CONFIGURATION"

    - name: Baixar JetBrains Mono Font Oficial
      ansible.builtin.get_url:
        url: https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
        dest: /tmp/JetBrainsMono.zip
        checksum: sha256:87e989d2f715f185be31e472dd4e95e9c42eff216a25244664fbe53d3f

    - name: Crie diretório de fontes
      file:
        path: /usr/share/fonts/truetype/jetbrains-mono
        state: directory

    - name: Descompactar JetBrains Mono Font Oficial
      unarchive:
        src: /tmp/JetBrainsMono.zip
        dest: /usr/share/fonts/truetype/jetbrains-mono
        remote_src: yes
        include:
          - '*.ttf'
          - '*.woff2'

    - name: Atualize cache de fontes
      command: fc-cache -f -v

    - name: Instalar Oh My Zsh
      become_user: "{{ ansible_user_id }}"
      ansible.builtin.shell: 
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" 
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

    - name: Configurar Zsh como shell padrão
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: Instalar uv (ferramenta da Astral)
      ansible.builtin.shell: 
        cmd: curl -LsSf https://astral.sh/uv/install.sh | sh
        creates: "{{ ansible_env.HOME }}/.cargo/bin/uv"

    - name: Adicionar uv ao PATH
      become_user: "{{ ansible_user_id }}"
      blockinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        block: |
          # uv configuration
          export PATH="{{ ansible_env.HOME }}/.cargo/bin:$PATH"
        create: yes
        marker: "# {mark} UV CONFIGURATION"

  handlers:
    - name: update-fonts
      command: fc-cache -f -v
