- name: Playbook
  hosts: localhost
  tasks:
    - name: Update all packages
      become: true
      community.general.zypper:
        name: "*"
        state: latest
    
    - name: Add VsCode repository
      become: true
      community.general.zypper_repository:
        name: vscode
        repo: https://packages.microsoft.com/yumrepos/vscode
        state: present
        auto_import_keys: true
        runrefresh: true

    - name: Add Edge repository
      become: true
      community.general.zypper_repository:
        name: microsoft-edge
        repo: https://packages.microsoft.com/yumrepos/edge
        state: present
        auto_import_keys: true
        runrefresh: true

    - name: Add Github-Cli repository
      become: true
      community.general.zypper_repository:
        repo: https://cli.github.com/packages/rpm/gh-cli.repo
        state: present
        auto_import_keys: true
        runrefresh: true
        disable_gpg_check: true

    - name: Install packages
      become: true
      community.general.zypper:
        name:
          - zsh
          - vim
          - git
          - curl
          - wget
          - unzip
          - code
          - gh
          - podman
          - buildah
          - microsoft-edge-stable          
        state: present
    
    - name: Zsh Path
      ansible.builtin.shell: which zsh
      args:
        executable: /bin/bash
      register: path
    
    - name: Set ZSH default shell
      become: true
      ansible.builtin.user:
        name: fabio
        shell: "{{ path.stdout }}"

    - name: Install Oh My Zsh
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh
        dest: ~/.oh-my-zsh
        depth: 1
 
    - name: Install zsh-autosuggestions plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1

    - name: Install zsh-history-substring-search plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-history-substring-search
        dest: ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search
        depth: 1

    - name: Install zsh-completions plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
        depth: 1
 
    - name: Install zsh-syntax-highlighting plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        depth: 1
    
    - name: Ensure fonts directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: JetBrains exists
      ansible.builtin.shell: "ls {{ lookup('env', 'HOME') }}/.fonts/JetBrains*"
      register: jetbrains_exists
      ignore_errors: yes

    - name: Download JetBrains
      when: jetbrains_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes

    - name: Update Fonts
      when: jetbrains_exists is failed
      ansible.builtin.shell: "fc-cache -vf"
      ignore_errors: yes