- name: Playbook
  hosts: localhost
  tasks:
    - name: Update all packages
      become: true
      community.general.zypper:
        name: "*"
        state: latest

    - name: Add VsCode repository
      become: true
      community.general.zypper_repository:
        name: vscode
        repo: https://packages.microsoft.com/yumrepos/vscode
        state: present
        auto_import_keys: true
        runrefresh: true

    - name: Add Edge repository
      become: true
      community.general.zypper_repository:
        name: microsoft-edge
        repo: https://packages.microsoft.com/yumrepos/edge
        state: present
        auto_import_keys: true
        runrefresh: true

    - name: Add Github-Cli repository
      become: true
      community.general.zypper_repository:
        repo: https://cli.github.com/packages/rpm/gh-cli.repo
        state: present
        auto_import_keys: true
        runrefresh: true
        disable_gpg_check: true

    - name: Install packages
      become: true
      community.general.zypper:
        name:
          - zsh
          - vim
          - git
          - curl
          - wget
          - unzip
          - code
          - gh
          - podman
          - buildah
          - microsoft-edge-stable
        state: present

    - name: Check uv install
      ansible.builtin.shell:
        cmd: uv version
        executable: "{{ ansible_env.SHELL }}"
      register: uv_install_status
      changed_when: uv_install_status == 0

    - name: Download script uv install
      ansible.builtin.get_url:
        url: https://astral.sh/uv/install.sh
        dest: /tmp/uv-install.sh
        mode: "0755"
      changed_when: uv_install_status.rc != 0

    - name: Install uv
      ansible.builtin.shell:
        cmd: /tmp/uv-install.sh
        executable: /bin/bash
      changed_when: uv_install_status.rc != 0

    - name: Zsh Path
      ansible.builtin.shell: which zsh
      args:
        executable: /bin/bash
      register: path
      changed_when: path.rc != 0

    - name: Set ZSH default shell
      become: true
      ansible.builtin.user:
        name: fabio
        shell: "{{ path.stdout }}"

    - name: Install Oh My Zsh
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh
        dest: ~/.oh-my-zsh
        depth: 1
        version: 69a6359f7cf8978d464573fb7b023ee3cd00181a

    - name: Install zsh-autosuggestions plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1
        version: 0e810e5afa27acbd074398eefbe28d13005dbc15

    - name: Install zsh-history-substring-search plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-history-substring-search
        dest: ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search
        depth: 1
        version: 87ce96b1862928d84b1afe7c173316614b30e301

    - name: Install zsh-completions plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
        depth: 1
        version: 6ff1a671a8177ebdb356dd566e557c2db79759a2

    - name: Install zsh-syntax-highlighting plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        depth: 1
        version: 5eb677bb0fa9a3e60f0eff031dc13926e093df92

    - name: Create a zshrc
      ansible.builtin.get_url:
        url: https://gist.githubusercontent.com/f4biogr/f80bd3d7b97b89d669090261e7b12b65/raw/e063388e102977d46ed8b18b69933da01529bdd9/.zshrc
        dest: "{{ ansible_env.HOME }}/.zshrc"
        mode: "644"
        owner: 1000
        group: 100

    - name: Ensure fonts directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory
        mode: "0755"

    - name: JetBrains exists
      ansible.builtin.shell: "ls {{ lookup('env', 'HOME') }}/.fonts/JetBrains*"
      register: jetbrains_exists
      changed_when: jetbrains_exists.rc == 0
      ignore_errors: true

    - name: Download JetBrains
      when: jetbrains_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: true

    - name: Update Fonts
      when: jetbrains_exists is failed
      ansible.builtin.command: "fc-cache -vf"
      changed_when: jetbrains_exists.rc == 0
