name: Ansible Lint and Format

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible-lint
        ansible-galaxy collection install community.general

    - name: Run ansible-lint
      run: |
        ansible-lint playbooks/
